# Generated by Django 2.1.2 on 2018-10-17 09:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_datetime', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), verbose_name='データ日時')),
                ('temp_out', models.FloatField(verbose_name='temp_out')),
                ('temp_in', models.FloatField(verbose_name='temp_in')),
                ('temp_set', models.FloatField(verbose_name='temp_set')),
                ('temp_vent', models.FloatField(verbose_name='temp_vent')),
                ('temp_heat', models.FloatField(verbose_name='temp_heat')),
                ('temp_soil', models.FloatField(verbose_name='temp_soil')),
                ('rh_out', models.FloatField(verbose_name='rh_out')),
                ('rh_in', models.FloatField(verbose_name='rh_in')),
                ('rain', models.FloatField(verbose_name='rain')),
                ('irradiance', models.FloatField(verbose_name='irradiance')),
                ('co2_conc', models.FloatField(verbose_name='co2_conc')),
                ('co2_set', models.FloatField(verbose_name='co2_set')),
                ('net_photos', models.FloatField(verbose_name='net_photos')),
                ('transpiration', models.FloatField(verbose_name='transpiration')),
                ('head_load', models.FloatField(verbose_name='head_load')),
                ('head_load_pu', models.FloatField(verbose_name='head_load_pu')),
                ('control_mode', models.FloatField(verbose_name='control_mode')),
                ('night_cool_mode', models.FloatField(verbose_name='night_cool_mode')),
                ('window_opening', models.FloatField(verbose_name='window_opening')),
                ('window_kp', models.FloatField(verbose_name='window_kp')),
                ('curtain_mode', models.FloatField(verbose_name='curtain_mode')),
                ('hp_heat', models.FloatField(verbose_name='hp_heat')),
                ('hp_cool', models.FloatField(verbose_name='hp_cool')),
                ('hf', models.FloatField(verbose_name='hf')),
                ('mist', models.FloatField(verbose_name='mist')),
                ('exhaust_fun', models.FloatField(verbose_name='exhaust_fun')),
                ('co2', models.FloatField(verbose_name='co2')),
                ('co2_sec', models.FloatField(verbose_name='co2_sec')),
                ('dehumidify', models.FloatField(verbose_name='dehumidify')),
                ('fan_mode', models.FloatField(verbose_name='fan_mode')),
                ('fan_speed', models.FloatField(verbose_name='fan_speed')),
                ('shutter', models.FloatField(verbose_name='shutter')),
                ('fan2_mode', models.FloatField(verbose_name='fan2_mode')),
                ('fan2_speed', models.FloatField(verbose_name='fan2_speed')),
                ('shutter2', models.FloatField(verbose_name='shutter2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'greenhouse',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ロケーション名')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.Location', verbose_name='ロケーション'),
        ),
        migrations.AlterUniqueTogether(
            name='greenhouse',
            unique_together={('location', 'data_datetime')},
        ),
    ]
